project:
  name: marstech-link-spray
  description: Web application to open multiple URLs with a single click
  authors:
    - Stéphane ROBIN
  license: MIT
  java:
    version: 21

release:
  github:
    owner: alkaphreak
    name: marstech-link-spray
    tagName: 'v{{projectVersion}}'
    releaseName: 'Release v{{projectVersion}}'
    overwrite: true
    branch: 'release/v{{projectVersion}}'
    changelog:
      formatted: ALWAYS
      preset: conventional-commits

distributions:
  marstech-link-spray:
    type: JAVA_BINARY
    artifacts:
      - path: 'target/mt-link-spray-{{projectVersion}}.jar'

packagers:
  docker:
    active: ALWAYS
    repository:
      active: RELEASE
      owner: '{{DOCKER_HUB_USERNAME}}'
      name: '{{DOCKER_REPO}}'
    registries:
      - serverName: DEFAULT
        server: docker.io
        username: '{{DOCKER_HUB_USERNAME}}'
        password: '{{DOCKER_HUB_ACCESS_TOKEN}}'
    imageNames:
      - '{{DOCKER_HUB_USERNAME}}/{{DOCKER_REPO}}:{{tagName}}'
      - '{{DOCKER_HUB_USERNAME}}/{{DOCKER_REPO}}:latest'