name: Maven Publish

on:
  release:
    types: [ created ]

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Java 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'liberica'
          server-id: github
          settings-path: ${{ github.workspace }}
          cache: maven

      - name: Verify Java version
        run: java -version

      - name: Verify Maven settings
        run: cat ${{ github.workspace }}/settings.xml

      - name: Build with Maven
        run: mvn -B clean install --file pom.xml

      - name: Run tests and upload Surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/

      - name: Upload JaCoCo coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/

      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B deploy --file pom.xml

      # Optional: Clean up artifacts to save space
      - name: Cleanup workspace
        if: always()
        run: rm -rf target